### PR TITLE
useful extensions and enhancements

### PR DESCRIPTION
**Pull request by TheTesla**
predict() is now overloaded. You can specify image file name or an raw rgb image matrix (opencv). Additional function plot_pose_stickmodel_cv2mat() does the same like plot_pose_stickmodel() but uses opencv and plots the stickmodel in an opencv mat, which is returned by the function. It can be used for video processing to make a video showing the stickmodel. PoseIEF, get_scale_net() and get_pose_net() have now the possibility to specify the gpu id or cpu mode by setting gpu=False

### CODE REVIEW

**Comment by pulkitag** [comment]
@TheTesla I will have a look at them soon and merge them. Thanks for the contribution.

**Comment by pulkitag** [comment]
@TheTesla - couple of things:
(1) pycaffe_utils is not part of the IEF code release. Your current pull request depends on some changes to pycaffe_utils. I can merge those changes if you make a pull request at [link](https://github.com/pulkitag/pycaffe-utils).

(2) cv2 is notorious to install and run on machines where one doesnot has admin access. I am planning to remove cv2 as a dependency. At the same time, it would be great to have the cv2 utilities as many people prefer to use it. One way to merge the changes that you proposed is to also include a check when cv2 is imported. (See [here](https://github.com/pulkitag/pycaffe-utils/blob/master/my_pycaffe.py#L18) for an example). 

(3) Lets keep the code fully pythonic. I noticed you have included the option gpu = 0. The pythonic way would be gpu = False. 

Having said that - it would be great to have the extra functionality merged with the master branch.

**Comment by TheTesla** [comment]
(1) was not intented to change by me. It is a unwanted submodule commit. I installed the special version of caffe in the ief project. 

(2) Yes I can add the check. Should it only print the warning, what functions can't be used?

(3) What do you mean? I thought gpu=0 is the first gpu and gpu=False is the cpu. Would it be better to use two variables, one telling which one gpu or cpu and a second one telling which gpu? Like it is done in my_pycaffe? isGPU=True - use gpu; deviceId=0 - use the first one?

**Comment by pulkitag** [comment]
(1) Let me see what needs to be done for unwanted submodule commits. 

(2) Yes, just a check that prints that cv2 is missing and some functions maynot work properly is sufficient for now. 

(3) Yes, its always good when the type of variables is not changed. For instance gpu = False, gpu=0 both satisfy the condition gpu == False. This kind of overriding may lead to bugs in the future.

**Comment by TheTesla** [comment]
Now I have done the work.The video processing needs also opencv. Please let me know if I should change something.

**Comment by pulkitag** [comment]
Merged! One thing that would be interesting to try for videos  is instead of using 3 or 4 IEF iterations, just use one iteration for every frame - as the person will not change by that much between consequent frames.

**Comment by TheTesla** [comment]
Yes, I tried it. Please look at my fork:

https://github.com/TheTesla/ief

At first I had to recompose the predict method. A lot of time is consumed by crop and scale as preparation for the netScale (16 ms). The netScale took also 34 ms. This is the first thing to optimize. In my test, I had a video where the scaleIdx was 0 the whole time. So I tried to make it fix for the test. It worked.

But now about the iteration loop: I have modified the predict method to consume the currPose as parameter. The number of iterations is also a parameter. At first I used the currPose result as initialisation for the next image and it was a very bad result. There was a runaway and a stuck effect. The legs were growing until it crashed. The arms didn't ever respond.

So I extended the predict method to weight the currPose feedback loop. A value of 0 means no feedback, initialize with seedPose_ for every image. A value of 1 for loopfactor means use last currPose result for initilisation. So I tried different values and found the loopfactor=0.1 is ok, but doesn't have a visible effect. A value of 0.2 has visible results but bad one. It seams that the remaining error is accumulated not compensated. I got the same effect useing a huge amount of iterations (200).

I don't know why the algorithm is not stable or does not convergate. May be the netPose should be trained to be stable on an infinite amount of iterations?

**Comment by pulkitag** [comment]
I am going to pull in your PR sometime this week and try it out. In the meanwhile, if you can share some visuals of the failure mode it would be great. 

Regarding training, I am working on the code release for it. We should have it soon - it would be easier to try out training related ideas then.

**Comment by TheTesla** [comment]
Here are some visuals of the failure mode:

https://www.youtube.com/playlist?list=PLKkMt1aWZPrrHZOulPuZWl0eOqwYNrx4_

**Comment by pulkitag** [comment]
Thanks for posting this. There are atleast two failure modes:
1. When the person is significantly occluded. 
2. The iterative estimation drifts away or as you mentioned the convergence is not stable. 

One reason for convergence not being stable is that pose detection was always trained from the mean pose. We managed to train some new models that are initialized from random poses and that should help convergence. I will be posting these models after the CVPR camera ready deadline.

For (1), we need to train with occluded images - MPII is very biased in the kind of data it has. I don't see any easy way fixes for (1).

**Pull request merged**
